Convert setup
NorfairKing/smos-poc pull request #6
Opened 2018-01-28 17:48 UTC by Nickske666

2018-01-28 18:23 UTC, NorfairKing requested changes
Almost exactly the same review as last time. Please first review the PR yourself before requesting review.

2018-01-28 18:23 UTC, NorfairKing commented on smos-convert/package.yaml
> +license:             BSD3
AllRightsReserved

2018-01-28 18:23 UTC, NorfairKing commented on smos-convert/src/Import.hs
> +import GHC.Generics as X hiding (to)
Only import `Generic` instead of only hiding `to`.

2018-01-28 18:23 UTC, NorfairKing commented on smos-convert/src/Smos/Convert/OptParse.hs
> +parseCommand = hsubparser $ command "convert" parseConvertFile
So the command will be `smos-convert convert FILE`? Why not just `smos-convert FILE`?

2018-01-28 18:23 UTC, NorfairKing commented on smos-convert/test/Spec.hs
> +main = putStrLn "Test suite not yet implemented"
Just leave it out then.

2018-01-28 18:23 UTC, NorfairKing commented on smos-data/src/Smos/Data/Types.hs
> +               [ isNothing entryContents
No cosmetic changes here please.

2018-01-28 19:54 UTC, Nickske666 commented on smos-convert/test/Spec.hs
> +main = putStrLn "Test suite not yet implemented"
I don't understand why.
I added this as a reminder that I need to add tests.
What do you want to replace it by, and more importantly, what is wrong with this?

2018-02-03 09:33 UTC, NorfairKing requested changes

2018-02-03 09:33 UTC, NorfairKing commented on smos/src/Smos/Draw.hs
> +    map
No cosmetic changes.

2018-02-03 20:40 UTC, Nickske666 commented
I only changed the one comment you made.
Everything is good now.

2018-02-03 20:41 UTC, closed without merging